# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'LOOKHEART 100' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LOOKHEART 100

pod 'KeychainSwift'
pod 'Firebase/Auth'
end
